// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(SchoolBookContext))]
    partial class SchoolBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Grade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 481, DateTimeKind.Local).AddTicks(6284),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 481, DateTimeKind.Local).AddTicks(6315),
                            Score = 5.0,
                            StudentID = 1,
                            SubjectID = 1
                        },
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 482, DateTimeKind.Local).AddTicks(16),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 482, DateTimeKind.Local).AddTicks(45),
                            Score = 5.0,
                            StudentID = 2,
                            SubjectID = 2
                        });
                });

            modelBuilder.Entity("Models.JoiningModels.ParentStudent", b =>
                {
                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ParentID", "StudentID");

                    b.HasIndex("StudentID");

                    b.ToTable("ParentStudents");

                    b.HasData(
                        new
                        {
                            ParentID = 1,
                            StudentID = 1
                        },
                        new
                        {
                            ParentID = 1,
                            StudentID = 2
                        });
                });

            modelBuilder.Entity("Models.JoiningModels.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("TeacherID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            TeacherID = 2,
                            SubjectID = 1
                        },
                        new
                        {
                            TeacherID = 2,
                            SubjectID = 2
                        },
                        new
                        {
                            TeacherID = 1,
                            SubjectID = 1
                        });
                });

            modelBuilder.Entity("Models.Parent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(647),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(708),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(4014),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(4050),
                            UserID = 3
                        },
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(8605),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(8637),
                            UserID = 5
                        });
                });

            modelBuilder.Entity("Models.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(9937),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(9967),
                            Name = "Subject1"
                        },
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 481, DateTimeKind.Local).AddTicks(1434),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 481, DateTimeKind.Local).AddTicks(1463),
                            Name = "Subject2"
                        });
                });

            modelBuilder.Entity("Models.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(6694),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(6727),
                            UserID = 4
                        },
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(8775),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 480, DateTimeKind.Local).AddTicks(8787),
                            UserID = 6
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 434, DateTimeKind.Local).AddTicks(6153),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 439, DateTimeKind.Local).AddTicks(8763),
                            Email = "Admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "AMnHRwYCX1I3KuWctiQLv2HpsZ1Vj9yA1gJngmvNI0A9W02GsQJycUY6fnJOR99FlQ==",
                            Role = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 469, DateTimeKind.Local).AddTicks(9023),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 469, DateTimeKind.Local).AddTicks(9101),
                            Email = "Parent@gmail.com",
                            FirstName = "Parent",
                            LastName = "Parent",
                            Password = "ALYgCHthIKBQTZK0LYENw/YPXH5NNHH1tmofpIXgFKf6ZmjfJqOWOrrXeBvqfg4YSQ==",
                            Role = "Parent"
                        },
                        new
                        {
                            ID = 3,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 472, DateTimeKind.Local).AddTicks(1338),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 472, DateTimeKind.Local).AddTicks(1394),
                            Email = "Student@gmail.com",
                            FirstName = "Student",
                            LastName = "Student",
                            Password = "AP3cinWj6ZZNu+/+MBNJ/Qvldymc2ih5k3mLDoltiII5Og3fBqdmkFbgP2k+D+u+Kg==",
                            Role = "Student"
                        },
                        new
                        {
                            ID = 4,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 473, DateTimeKind.Local).AddTicks(4629),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 473, DateTimeKind.Local).AddTicks(4658),
                            Email = "Teacher@gmail.com",
                            FirstName = "Teacher",
                            LastName = "Teacher",
                            Password = "AI9gIeponffvPbbkkf7rkpJ+8eMIQZljBWHTsqC0KpkPKvrBrZCl8Xya/8yQBVxxbw==",
                            Role = "Teacher"
                        },
                        new
                        {
                            ID = 5,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 474, DateTimeKind.Local).AddTicks(8855),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 474, DateTimeKind.Local).AddTicks(8918),
                            Email = "Student2@gmail.com",
                            FirstName = "Student2",
                            LastName = "Student2",
                            Password = "AHb4rvWapfJeOXcgBFRfMNg/X34W+IAF+hnQTnXJ/yidEsGyBN7MMvhPFttCXdmh4g==",
                            Role = "Student"
                        },
                        new
                        {
                            ID = 6,
                            DateCreated = new DateTime(2020, 1, 17, 10, 36, 23, 477, DateTimeKind.Local).AddTicks(3488),
                            DateModified = new DateTime(2020, 1, 17, 10, 36, 23, 477, DateTimeKind.Local).AddTicks(3552),
                            Email = "Teacher2@gmail.com",
                            FirstName = "Teacher2",
                            LastName = "Teacher2",
                            Password = "AGn857s4/ZdasogaPqxuCPq5x6lEb59fBknks/G/H+H5A1xk0NCNHvDZ2oMYGz3YeA==",
                            Role = "Teacher"
                        });
                });

            modelBuilder.Entity("Models.UserToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Models.Grade", b =>
                {
                    b.HasOne("Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentID");

                    b.HasOne("Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectID");
                });

            modelBuilder.Entity("Models.JoiningModels.ParentStudent", b =>
                {
                    b.HasOne("Models.Parent", "Parent")
                        .WithMany("ParentStudents")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Student", "Student")
                        .WithMany("ParentStudents")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.JoiningModels.TeacherSubject", b =>
                {
                    b.HasOne("Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Parent", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("Models.Parent", "UserID");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Models.Student", "UserID");
                });

            modelBuilder.Entity("Models.Teacher", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("Models.Teacher", "UserID");
                });

            modelBuilder.Entity("Models.UserToken", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
